/**
 * add-movies.js
 * Script thêm phim vào database MÀ KHÔNG XÓA dữ liệu cũ.
 * Chỉ chèn phim nếu chưa tồn tại (kiểm tra theo title).
 * Chạy: node src/add-movies.js
 */
require('dotenv').config();
const mongoose = require('mongoose');
const Movie = require('./models/Movie.model');

const newMovies = [
  {
    title: 'Spider-Man: No Way Home',
    titleEN: 'Spider-Man: No Way Home',
    description: 'Peter Parker nhờ Bác Sĩ Strange thực hiện phép thuật để thế giới quên đi danh tính người Nhện của anh, nhưng phép thuật mở ra đa vũ trụ, triệu hồi những kẻ phản diện nguy hiểm nhất.',
    descriptionEN: 'Peter Parker seeks help from Doctor Strange to make the world forget he is Spider-Man, but the spell opens the multiverse, summoning the most dangerous villains from alternate realities.',
    duration: 148,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2021-12-17'),
    posterUrl: 'https://image.tmdb.org/t/p/original/1g01tZ55ehgcLIZk0Z7neJt7ZtY.jpg',
    trailerUrl: 'https://www.youtube.com/embed/JfVOs4VSpmA',
    rating: 'T13',
    director: 'Jon Watts',
    cast: ['Tom Holland', 'Zendaya', 'Benedict Cumberbatch', 'Jacob Batalon'],
    status: 'ended',
  },
  {
    title: 'Black Panther: Wakanda Forever',
    titleEN: 'Black Panther: Wakanda Forever',
    description: "Sau khi mất đi vị vua T'Challa, người dân Wakanda phải bảo vệ đất nước khỏi sự xâm lược của Namor và vương quốc Talokan dưới lòng đại dương.",
    descriptionEN: "After losing King T'Challa, the people of Wakanda must protect their nation from the invasion of Namor and the underwater kingdom of Talokan.",
    duration: 161,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2022-11-11'),
    posterUrl: 'https://image.tmdb.org/t/p/original/sv1Alw5gTGlR3I3xo68efrYrD4j.jpg',
    trailerUrl: 'https://www.youtube.com/embed/_Z3QKkl1WyM',
    rating: 'T13',
    director: 'Ryan Coogler',
    cast: ['Letitia Wright', 'Lupita Nyong\'o', 'Danai Gurira', 'Winston Duke'],
    status: 'ended',
  },
  {
    title: 'Thor: Love and Thunder',
    titleEN: 'Thor: Love and Thunder',
    description: 'Thor bắt đầu hành trình tìm kiếm sự bình yên, nhưng phải đối mặt với Gorr kẻ giết thần linh đang tìm cách tiêu diệt tất cả các vị thần. Jane Foster trở thành Nữ Thor huyền thoại.',
    descriptionEN: 'Thor embarks on a journey of self-discovery but must interrupt it to face Gorr the God Butcher, who seeks to make the gods extinct. Along the way, Jane Foster wields Mjolnir as the Mighty Thor.',
    duration: 119,
    genre: ['Action', 'Adventure', 'Fantasy'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2022-07-08'),
    posterUrl: 'https://image.tmdb.org/t/p/original/pIk4GJeLHubuEVIIFYxaCgIS1dC.jpg',
    trailerUrl: 'https://www.youtube.com/embed/Go8nTmfrQd8',
    rating: 'T13',
    director: 'Taika Waititi',
    cast: ['Chris Hemsworth', 'Christian Bale', 'Tessa Thompson', 'Jaimie Alexander'],
    status: 'ended',
  },
  {
    title: 'Shang-Chi and the Legend of the Ten Rings',
    titleEN: 'Shang-Chi and the Legend of the Ten Rings',
    description: 'Shang-Chi bị kéo vào thế giới bí ẩn của tổ chức Thập Nhẫn và phải đối đầu với chính người cha quyền năng của mình, đồng thời khám phá bí mật về quá khứ của gia đình.',
    descriptionEN: "Shang-Chi is drawn into the world of the Ten Rings and must confront his powerful father while uncovering secrets about his family's past.",
    duration: 132,
    genre: ['Action', 'Adventure', 'Fantasy'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2021-09-03'),
    posterUrl: 'https://image.tmdb.org/t/p/original/xeMwZ12574e4XGvj4E3g0B0G6F8.jpg',
    trailerUrl: 'https://www.youtube.com/embed/8YjFMR4jWZO',
    rating: 'T13',
    director: 'Destin Daniel Cretton',
    cast: ['Simu Liu', 'Awkwafina', 'Tony Leung', 'Michelle Yeoh'],
    status: 'ended',
  },
  {
    title: 'Eternals',
    titleEN: 'Eternals',
    description: 'Nhóm anh hùng bất tử Eternals tái hợp sau hàng nghìn năm để bảo vệ Trái Đất khỏi kẻ thù cổ xưa nhất của họ - các Deviant đột biến nguy hiểm.',
    descriptionEN: 'The immortal Eternals reunite after thousands of years to protect Earth from their ancient enemies — the mutated and dangerous Deviants.',
    duration: 156,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2021-11-05'),
    posterUrl: 'https://image.tmdb.org/t/p/original/bcCBq5N3YvKd09oY27NL354B55q.jpg',
    trailerUrl: 'https://www.youtube.com/embed/x_me3xsvDgk',
    rating: 'T13',
    director: 'Chloé Zhao',
    cast: ['Gemma Chan', 'Richard Madden', 'Kumail Nanjiani', 'Lia McHugh'],
    status: 'ended',
  },
  {
    title: 'Encanto',
    titleEN: 'Encanto',
    description: 'Gia đình Madrigal sống trong một ngôi nhà thần kỳ ở vùng núi Colombia, nơi mỗi người đều có một phép năng đặc biệt - trừ Mirabel. Khi phép màu của ngôi nhà bắt đầu biến mất, chỉ có cô mới có thể cứu gia đình.',
    descriptionEN: "The Madrigal family lives in a magical house in the mountains of Colombia, where every family member has a unique gift—except Mirabel. When the house's magic starts fading, only she can save the family.",
    duration: 102,
    genre: ['Animation', 'Comedy', 'Family', 'Fantasy'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2021-11-24'),
    posterUrl: 'https://image.tmdb.org/t/p/original/4j0HT4mryX0mgo2r7Qz4AhpCmje.jpg',
    trailerUrl: 'https://www.youtube.com/embed/CaimKeNp45k',
    rating: 'P',
    director: 'Jared Bush, Byron Howard',
    cast: ['Stephanie Beatriz', 'María Cecilia Botero', 'John Leguizamo', 'Mauro Castillo'],
    status: 'ended',
  },
  {
    title: 'The Batman',
    titleEN: 'The Batman',
    description: 'Batman bước vào năm thứ hai làm người bảo vệ Gotham, buộc phải điều tra tội ác gây ra bởi kẻ giết người hàng loạt tên Riddler, dần khám phá sự thối nát ăn sâu vào thành phố.',
    descriptionEN: 'In his second year of fighting crime, Batman uncovers corruption in Gotham City while investigating a series of sadistic killings orchestrated by a mysterious murderer known as the Riddler.',
    duration: 176,
    genre: ['Action', 'Crime', 'Drama', 'Mystery'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2022-03-04'),
    posterUrl: 'https://image.tmdb.org/t/p/original/74xTEgt7R36FwEU567uBsNAVXGc.jpg',
    trailerUrl: 'https://www.youtube.com/embed/mqqft2x_Aa4',
    rating: 'T16',
    director: 'Matt Reeves',
    cast: ['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano', 'Jeffrey Wright'],
    status: 'ended',
  },
  {
    title: 'Top Gun: Maverick',
    titleEN: 'Top Gun: Maverick',
    description: 'Sau hơn 30 năm phục vụ, Pete "Maverick" Mitchell trở lại huấn luyện thế hệ phi công trẻ của Top Gun cho một nhiệm vụ đặc biệt đòi hỏi sự hy sinh cực đại.',
    descriptionEN: 'After more than 30 years of service, Pete "Maverick" Mitchell returns to train a group of Top Gun graduates for a specialized mission requiring the ultimate sacrifice.',
    duration: 130,
    genre: ['Action', 'Drama'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2022-05-27'),
    posterUrl: 'https://image.tmdb.org/t/p/original/62HCnUTziyWcpDaHu21alCXz2nQ.jpg',
    trailerUrl: 'https://www.youtube.com/embed/giXcoYkqwYY',
    rating: 'T13',
    director: 'Joseph Kosinski',
    cast: ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly', 'Jon Hamm'],
    status: 'ended',
  },
  {
    title: 'Avatar: The Way of Water',
    titleEN: 'Avatar: The Way of Water',
    description: 'Jake Sully và Neytiri cùng gia đình phải rời bỏ ngôi nhà và khám phá các vùng đất của Pandora. Khi mối nguy hiểm cổ đại tái xuất, họ phải chiến đấu để bảo vệ nhau.',
    descriptionEN: 'Jake Sully and Neytiri form a family and do what it takes to stay together. When trouble resurfaces, they must leave their home and explore the regions of Pandora.',
    duration: 192,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2022-12-16'),
    posterUrl: 'https://image.tmdb.org/t/p/original/t6HI7mg1jZ100W236BzZJ5mIyOH.jpg',
    trailerUrl: 'https://www.youtube.com/embed/d9MyW72ELq0',
    rating: 'T13',
    director: 'James Cameron',
    cast: ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Stephen Lang'],
    status: 'ended',
  },
  {
    title: 'Fast X',
    titleEN: 'Fast X',
    description: 'Dominic Toretto và gia đình phải đối mặt với Dante - kẻ thù nguy hiểm và lâu đời nhất từ trước đến nay, người đã lên kế hoạch trả thù suốt nhiều thập kỷ.',
    descriptionEN: "Dom Toretto and his family face Dante, the most ruthless villain they've ever encountered, a man who has been plotting revenge for decades.",
    duration: 141,
    genre: ['Action', 'Adventure', 'Thriller'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2023-05-19'),
    posterUrl: 'https://image.tmdb.org/t/p/original/fiVW06Jm7p4nE415mh5J5yH0Z4q.jpg',
    trailerUrl: 'https://www.youtube.com/embed/32RAq6JzY-w',
    rating: 'T16',
    director: 'Louis Leterrier',
    cast: ['Vin Diesel', 'Michelle Rodriguez', 'Tyrese Gibson', 'Ludacris'],
    status: 'ended',
  },
  {
    title: 'Mission: Impossible – Dead Reckoning Part One',
    titleEN: 'Mission: Impossible – Dead Reckoning Part One',
    description: 'Ethan Hunt và đội IMF phải truy đuổi một vũ khí có thể đe dọa toàn nhân loại trước khi nó rơi vào tay kẻ xấu.',
    descriptionEN: 'Ethan Hunt and the IMF team race against time to track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands.',
    duration: 163,
    genre: ['Action', 'Adventure', 'Thriller'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2023-07-12'),
    posterUrl: 'https://image.tmdb.org/t/p/original/NNxYBM4tr84nRAhXWwIT5v6xV2.jpg',
    trailerUrl: 'https://www.youtube.com/embed/2m1drlTOsdY',
    rating: 'T13',
    director: 'Christopher McQuarrie',
    cast: ['Tom Cruise', 'Hayley Atwell', 'Ving Rhames', 'Simon Pegg'],
    status: 'ended',
  },
  {
    title: 'Guardians of the Galaxy Vol. 3',
    titleEN: 'Guardians of the Galaxy Vol. 3',
    description: 'Peter Quill và nhóm Guardians lên đường bảo vệ Rocket trước quá khứ bí ẩn của anh. Hành trình sẽ thách thức nhóm đến giới hạn và có thể dẫn đến sự tan rã của họ.',
    descriptionEN: "Peter Quill rallies his team to defend Rocket from his past. The journey will challenge the Guardians to their limits and may lead to the team's disbandment.",
    duration: 150,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2023-05-05'),
    posterUrl: 'https://image.tmdb.org/t/p/original/r2J021crVeeHR6gC7M2gBwArw87.jpg',
    trailerUrl: 'https://www.youtube.com/embed/u3V5KDHRQVk',
    rating: 'T13',
    director: 'James Gunn',
    cast: ['Chris Pratt', 'Zoe Saldana', 'Dave Bautista', 'Karen Gillan'],
    status: 'ended',
  },
  {
    title: 'Oppenheimer',
    titleEN: 'Oppenheimer',
    description: 'Câu chuyện về J. Robert Oppenheimer - nhà vật lý người Mỹ đã đóng vai trò then chốt trong việc phát triển bom nguyên tử đầu tiên trong Dự án Manhattan.',
    descriptionEN: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II and the Manhattan Project.",
    duration: 180,
    genre: ['Biography', 'Drama', 'History'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2023-07-21'),
    posterUrl: 'https://image.tmdb.org/t/p/original/8Gxv2wSbs20L26d16qQ6t8i9yOh.jpg',
    trailerUrl: 'https://www.youtube.com/embed/uYPbbEG8y0g',
    rating: 'T18',
    director: 'Christopher Nolan',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'],
    status: 'ended',
  },
  {
    title: 'Barbie',
    titleEN: 'Barbie',
    description: 'Barbie sống trong thế giới hoàn hảo Barbieland bỗng dưng phải đối mặt với những khủng hoảng hiện sinh và bắt đầu một hành trình vào thế giới thực.',
    descriptionEN: 'Barbie suffers a crisis that leads her to question her world, and she sets off on a journey into the real world.',
    duration: 114,
    genre: ['Comedy', 'Family', 'Fantasy'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2023-07-21'),
    posterUrl: 'https://image.tmdb.org/t/p/original/iuFNMS8U5X6g0wqjV3hzbUjBEth.jpg',
    trailerUrl: 'https://www.youtube.com/embed/pBk4NYhWNMM',
    rating: 'T13',
    director: 'Greta Gerwig',
    cast: ['Margot Robbie', 'Ryan Gosling', 'America Ferrera', 'Kate McKinnon'],
    status: 'ended',
  },
  {
    title: 'Inside Out 2',
    titleEN: 'Inside Out 2',
    description: 'Riley bước vào tuổi thiếu niên và một loạt cảm xúc mới xuất hiện trong tâm trí cô bé, tạo ra sự hỗn loạn chưa từng có giữa Joy và những người bạn cũ.',
    descriptionEN: 'Riley enters her teenage years and a new set of Emotions show up just in time to cause havoc over a very important weekend.',
    duration: 96,
    genre: ['Animation', 'Comedy', 'Family', 'Fantasy'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2024-06-14'),
    posterUrl: 'https://image.tmdb.org/t/p/original/vpnVM9B6Vm6FJv6OTZ4xYiTyLh2.jpg',
    trailerUrl: 'https://www.youtube.com/embed/LEjhY2iUqLw',
    rating: 'P',
    director: 'Kelsey Mann',
    cast: ['Amy Poehler', 'Maya Hawke', 'Kensington Tallman', 'Liza Lapira'],
    status: 'now-showing',
  },
  {
    title: 'Deadpool & Wolverine',
    titleEN: 'Deadpool & Wolverine',
    description: 'Deadpool được tuyển vào TVA và cùng Wolverine thực hiện sứ mệnh quan trọng có thể thay đổi lịch sử Marvel mãi mãi.',
    descriptionEN: 'Deadpool is recruited by the TVA and teams up with Wolverine on a mission that could change the history of the Marvel Cinematic Universe forever.',
    duration: 128,
    genre: ['Action', 'Comedy', 'Sci-Fi'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2024-07-26'),
    posterUrl: 'https://image.tmdb.org/t/p/original/8cdWjvZVDmXZlhJ7Urw8dpmrjf5.jpg',
    trailerUrl: 'https://www.youtube.com/embed/8-_Z19c0jXg',
    rating: 'T18',
    director: 'Shawn Levy',
    cast: ['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin', 'Morena Baccarin'],
    status: 'now-showing',
  },
  {
    title: 'Moana 2',
    titleEN: 'Moana 2',
    description: 'Moana lên đường chinh phục vùng biển chưa được khám phá khi nhận được lời kêu gọi từ tổ tiên. Cô tập hợp thủy thủ đoàn và cùng nhau đối mặt với vùng biển đầy bí ẩn và nguy hiểm.',
    descriptionEN: 'Moana sets sail on a daring mission to a mysterious and magical region of the ocean, responding to an ancestral call. She crews an unlikely group of seafarers on an impossible journey.',
    duration: 100,
    genre: ['Animation', 'Adventure', 'Family'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2024-11-27'),
    posterUrl: 'https://image.tmdb.org/t/p/original/4t095crC5IS0AgF5Hj5ql55thOI.jpg',
    trailerUrl: 'https://www.youtube.com/embed/h7KuOpGPv90',
    rating: 'P',
    director: 'David G. Derrick Jr.',
    cast: ['Auli\'i Cravalho', 'Dwayne Johnson', 'Alan Tudyk', 'Temuera Morrison'],
    status: 'now-showing',
  },
  {
    title: 'Wicked',
    titleEN: 'Wicked',
    description: 'Câu chuyện về tình bạn bất ngờ giữa Elphaba - cô gái da xanh bị xa lánh - và Glinda - cô gái nổi tiếng và quyến rũ - tại trường phù thủy Shiz trước khi trở thành hai phù thủy huyền thoại của Oz.',
    descriptionEN: 'The story of the unlikely friendship between Elphaba — a misunderstood young woman with emerald-green skin — and Glinda, a popular and ambitious girl, long before they became the Wicked Witch and Glinda the Good.',
    duration: 160,
    genre: ['Fantasy', 'Musical', 'Romance'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2024-11-22'),
    posterUrl: 'https://image.tmdb.org/t/p/original/2EE4uT8xGgH12V3f2wU2rZk3V3e.jpg',
    trailerUrl: 'https://www.youtube.com/embed/6COmYeLsz4c',
    rating: 'P',
    director: 'Jon M. Chu',
    cast: ['Cynthia Erivo', 'Ariana Grande', 'Jonathan Bailey', 'Michelle Yeoh'],
    status: 'now-showing',
  },
  {
    title: 'Alien: Romulus',
    titleEN: 'Alien: Romulus',
    description: 'Một nhóm thanh niên trên thuộc địa không gian đối mặt với dạng sống nguy hiểm nhất trong vũ trụ khi khám phá một trạm không gian bị bỏ hoang giữa các vì sao.',
    descriptionEN: 'A group of young people on a deep space colony planet come face to face with the most terrifying life form in the universe while searching an abandoned space station.',
    duration: 119,
    genre: ['Sci-Fi', 'Horror', 'Thriller'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2024-08-16'),
    posterUrl: 'https://image.tmdb.org/t/p/original/b33r3nN5r19Z14tMKJ7Rx46Nnle.jpg',
    trailerUrl: 'https://www.youtube.com/embed/x0XDEJCWDhs',
    rating: 'T18',
    director: 'Fede Álvarez',
    cast: ['Cailee Spaeny', 'David Jonsson', 'Archie Renaux', 'Isabela Merced'],
    status: 'now-showing',
  },
  {
    title: 'Joker: Folie à Deux',
    titleEN: 'Joker: Folie à Deux',
    description: 'Arthur Fleck đang bị giam giữ tại Arkham trong khi đối mặt với phiên tòa về những tội ác của mình. Tại đây anh gặp Harley Quinn và cả hai cùng nhau bước vào câu chuyện tình yêu điên loạn.',
    descriptionEN: 'Arthur Fleck is incarcerated at Arkham while awaiting trial for his crimes. He comes across Harley Quinn and together they embark on a musical love story.',
    duration: 138,
    genre: ['Drama', 'Crime', 'Musical'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2024-10-04'),
    posterUrl: 'https://image.tmdb.org/t/p/original/aciKV1S5eN5hQY5Q49k0sXzG09H.jpg',
    trailerUrl: 'https://www.youtube.com/embed/xy8aJw1vYTo',
    rating: 'T18',
    director: 'Todd Phillips',
    cast: ['Joaquin Phoenix', 'Lady Gaga', 'Brendan Gleeson', 'Catherine Keener'],
    status: 'now-showing',
  },
  {
    title: 'Twisters',
    titleEN: 'Twisters',
    description: 'Các chuyên gia theo dõi cơn lốc xoáy phải đối mặt với mùa bão khốc liệt nhất từ trước đến nay khi những cơn lốc siêu mạnh tấn công vùng đồng bằng Mỹ.',
    descriptionEN: 'Storm trackers confront the most extreme tornado season in recorded history when terrifying tornadoes tear across the American plains.',
    duration: 122,
    genre: ['Action', 'Adventure', 'Thriller'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2024-07-19'),
    posterUrl: 'https://image.tmdb.org/t/p/original/pjnD086zXWTzbb777n1ic6wQd25.jpg',
    trailerUrl: 'https://www.youtube.com/embed/J7iDs5s3Baw',
    rating: 'T13',
    director: 'Lee Isaac Chung',
    cast: ['Daisy Edgar-Jones', 'Glen Powell', 'Anthony Ramos', 'Brandon Perea'],
    status: 'now-showing',
  },
  {
    title: 'A Quiet Place: Day One',
    titleEN: 'A Quiet Place: Day One',
    description: 'Câu chuyện về những ngày đầu tiên khi thế giới bị chiếm đóng bởi những sinh vật săn mồi theo âm thanh, theo dõi hành trình sinh tồn của người phụ nữ tên Sam tại New York.',
    descriptionEN: 'A story about the earliest days of the invasion of the sound-hunting creatures, following a woman named Sam through New York City on Day One of the apocalypse.',
    duration: 99,
    genre: ['Sci-Fi', 'Horror', 'Thriller'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2024-06-28'),
    posterUrl: 'https://image.tmdb.org/t/p/original/yrp1wNBB161J51krAhwq03bhcnF.jpg',
    trailerUrl: 'https://www.youtube.com/embed/YPY7J-flzE8',
    rating: 'T16',
    director: 'Michael Sarnoski',
    cast: ['Lupita Nyong\'o', 'Joseph Quinn', 'Alex Wolff', 'Djimon Hounsou'],
    status: 'now-showing',
  },
  {
    title: 'Transformers One',
    titleEN: 'Transformers One',
    description: 'Nguồn gốc chưa từng được kể về Optimus Prime và Megatron - từ những người bạn tốt nhất trên Cybertron đến kẻ thù không đội trời chung đã thay đổi lịch sử vũ trụ mãi mãi.',
    descriptionEN: 'The untold origin story of Optimus Prime and Megatron — better known as sworn enemies, they were once close friends on Cybertron before a fateful choice changed their destinies forever.',
    duration: 104,
    genre: ['Animation', 'Action', 'Sci-Fi', 'Adventure'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2024-09-20'),
    posterUrl: 'https://image.tmdb.org/t/p/original/qhb1qwc7SEFD55zo0t151z45nsG.jpg',
    trailerUrl: 'https://www.youtube.com/embed/u1K4gG5pXis',
    rating: 'P',
    director: 'Josh Cooley',
    cast: ['Chris Hemsworth', 'Brian Tyree Henry', 'Scarlett Johansson', 'Keegan-Michael Key'],
    status: 'now-showing',
  },
  {
    title: 'The Wild Robot',
    titleEN: 'The Wild Robot',
    description: 'Robot ROZZUM đơn vị 7134 bị mắc kẹt trên một hòn đảo hoang và phải học cách thích nghi với thiên nhiên. Cô nhận nuôi một chú ngỗng mồ côi và dần khám phá ý nghĩa của tình mẫu tử.',
    descriptionEN: 'A robot named ROZZUM unit 7134 (Roz) is stranded on a wild island and must learn to adapt. She adopts an orphaned gosling and begins to discover what it means to be a mother.',
    duration: 102,
    genre: ['Animation', 'Family', 'Sci-Fi'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2024-09-27'),
    posterUrl: 'https://image.tmdb.org/t/p/original/w1nZ265gLTz83VJ441qnuVgo0Rx.jpg',
    trailerUrl: 'https://www.youtube.com/embed/67t8Wy4x16c',
    rating: 'P',
    director: 'Chris Sanders',
    cast: ['Lupita Nyong\'o', 'Pedro Pascal', 'Kit Connor', 'Bill Nighy'],
    status: 'now-showing',
  },
  {
    title: 'Venom: The Last Dance',
    titleEN: 'Venom: The Last Dance',
    description: 'Eddie Brock và Venom bị truy đuổi bởi cả hai thế giới con người và cộng sinh. Họ phải đưa ra quyết định tối thượng đặt dấu chấm hết cho câu chuyện của cả hai.',
    descriptionEN: 'Eddie Brock and Venom are on the run, pursued by both worlds — human and symbiote. They must make a devastating decision that will bring their story to its end.',
    duration: 109,
    genre: ['Action', 'Sci-Fi', 'Adventure'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2024-10-25'),
    posterUrl: 'https://image.tmdb.org/t/p/original/aosm8LM2j35536tdg7FzoLE8CjV.jpg',
    trailerUrl: 'https://www.youtube.com/embed/__2bjWbetsA',
    rating: 'T13',
    director: 'Kelly Marcel',
    cast: ['Tom Hardy', 'Chiwetel Ejiofor', 'Juno Temple', 'Rhys Ifans'],
    status: 'now-showing',
  },
  {
    title: 'Doctor Strange in the Multiverse of Madness',
    titleEN: 'Doctor Strange in the Multiverse of Madness',
    description:
      'Bác Sĩ Strange cùng một cô thiếu niên bí ẩn có khả năng di chuyển giữa các vũ trụ song song phải đương đầu với vô số mối nguy hiểm, bao gồm các phiên bản thay thế của chính họ đang đe dọa xóa sổ hàng triệu sinh mạng.',
    descriptionEN:
      'Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including alternate-universe versions of himself, which threaten to wipe out millions across the multiverse.',
    duration: 126,
    genre: ['Action', 'Adventure', 'Fantasy'],
    language: 'Tiếng Anh kèm Phụ đề Tiếng Việt',
    releaseDate: new Date('2022-05-04'),
    posterUrl: 'https://image.tmdb.org/t/p/original/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg',
    trailerUrl: 'https://www.youtube.com/embed/aWzlQ2N6qqg',
    rating: 'T13',
    director: 'Sam Raimi',
    cast: [
      'Benedict Cumberbatch',
      'Elizabeth Olsen',
      'Chiwetel Ejiofor',
      'Rachel McAdams',
      'Benedict Wong',
    ],
    status: 'now-showing',
  },
  {
    title: 'Spirited Away',
    titleEN: 'Spirited Away',
    description:
      'Cô bé 10 tuổi Chihiro đang trên đường chuyển nhà cùng cha mẹ bỗng lạc vào thế giới thần linh kỳ bí. Để cứu cha mẹ bị biến thành lợn, cô phải làm việc trong nhà tắm thần linh và vượt qua vô số thử thách để tìm đường về nhà.',
    descriptionEN:
      'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    duration: 125,
    genre: ['Animation', 'Adventure', 'Family', 'Fantasy'],
    language: 'Japanese with Vietnamese Subtitles',
    releaseDate: new Date('2001-07-20'),
    posterUrl: 'https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    trailerUrl: 'https://www.youtube.com/embed/ByXuk9QqQkk',
    rating: 'P',
    director: 'Hayao Miyazaki',
    cast: ['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki'],
    status: 'now-showing',
  },
];

const run = async () => {
  try {
    console.log('🔌 Connecting to MongoDB...');
    await mongoose.connect(
      process.env.MONGODB_URI || 'mongodb://localhost:27017/movie-ticket-booking'
    );
    console.log('✅ Connected!\n');

    let added = 0;
    let skipped = 0;

    for (const movieData of newMovies) {
      const exists = await Movie.findOne({ title: movieData.title });
      if (exists) {
        console.log(`⏭️  Skipped (already exists): ${movieData.title}`);
        skipped++;
      } else {
        await Movie.create(movieData);
        console.log(`✅ Added: ${movieData.title}`);
        added++;
      }
    }

    console.log(`\n🎬 Done! Added: ${added} | Skipped: ${skipped}`);
    process.exit(0);
  } catch (err) {
    console.error('❌ Error:', err.message);
    process.exit(1);
  }
};

run();
